<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Sync Direction
    |--------------------------------------------------------------------------
    |
    | LCDS only supports one-way replication: Hostinger production (source)
    | to VPS standby (target). Reverse direction is intentionally blocked.
    |
    */

    'direction' => 'hostinger_to_vps',

    'checkpoint_path' => storage_path('app/private/db-sync/state.json'),
    'table_checkpoint_directory' => storage_path('app/private/db-sync/checkpoints'),

    'apply_lock_path' => storage_path('app/private/db-sync/.apply.lock'),

    'inbox_directory' => storage_path('app/private/db-sync/inbox'),

    'chunk_row_limit' => 2000,

    'require_vps_dark' => true,

    'enforce_target_host' => true,

    'forbidden_vps_commands' => [
        'queue:work',
        'schedule:run',
        'outbox:process',
        'cashfree:auto-recover-missing',
        'cashfree:recover-historical',
        'radiumbox:recover-sync',
    ],


    /*
    |--------------------------------------------------------------------------
    | Source — Hostinger production
    |--------------------------------------------------------------------------
    */

    'source' => [
        'name' => 'hostinger',
        'label' => 'Hostinger Production',
        'ssh_host' => '187.127.183.72',
        'ssh_port' => 65002,
        'ssh_user' => 'u215544208',
        'project_path' => '/home/u215544208/laravel/radium-desk',
        'php_bin' => '/opt/alt/php84/usr/bin/php',
    ],

    /*
    |--------------------------------------------------------------------------
    | Target — VPS radium-1
    |--------------------------------------------------------------------------
    */

    'target' => [
        'name' => 'vps',
        'label' => 'VPS radium-1',
        'ssh_host' => '148.113.8.82',
        'ssh_port' => 20097,
        'ssh_user' => 'ravi',
        'project_path' => '/var/www/radium-desk',
        'php_bin' => '/usr/local/lsws/lsphp84/bin/php',
    ],

    /*
    |--------------------------------------------------------------------------
    | Table Manifest
    |--------------------------------------------------------------------------
    |
    | sync_order controls FK-safe apply order (lower runs first).
    | unique_indexes are business conflict indexes checked before Phase 2 upsert.
    |
    */

    'tables' => [

        // --- Tier 1: reference + identity (order 10) ---
        'users' => [
            'tier' => 1,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['email']],
            'soft_deletes' => true,
        ],
        'permissions' => [
            'tier' => 1,
            'sync_order' => 10,
            'strategy' => 'full_replace',
            'primary_key' => ['id'],
            'unique_indexes' => [['name', 'guard_name']],
        ],
        'roles' => [
            'tier' => 1,
            'sync_order' => 10,
            'strategy' => 'full_replace',
            'primary_key' => ['id'],
            'unique_indexes' => [['name', 'guard_name']],
        ],
        'device_models' => [
            'tier' => 1,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['name']],
        ],
        'reference_sequences' => [
            'tier' => 1,
            'sync_order' => 10,
            'strategy' => 'string_pk',
            'primary_key' => ['name'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['name']],
        ],
        'finance_payment_methods' => [
            'tier' => 1,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['name']],
        ],
        'finance_expense_categories' => [
            'tier' => 1,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['name']],
        ],
        'finance_cash_accounts' => [
            'tier' => 1,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['name']],
        ],
        'finance_bank_accounts' => [
            'tier' => 1,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['name']],
        ],
        'finance_settings' => [
            'tier' => 1,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['key']],
        ],
        'system_settings' => [
            'tier' => 2,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['key']],
        ],
        'settings' => [
            'tier' => 2,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['key']],
        ],
        'setting_products' => [
            'tier' => 2,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'setting_sources' => [
            'tier' => 2,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['key']],
        ],
        'company_holidays' => [
            'tier' => 2,
            'sync_order' => 10,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],

        // --- Tier 1: dependents of reference tables (order 20) ---
        'model_has_permissions' => [
            'tier' => 1,
            'sync_order' => 20,
            'strategy' => 'composite_pk',
            'primary_key' => ['permission_id', 'model_id', 'model_type'],
            'depends_on' => ['permissions', 'users'],
        ],
        'model_has_roles' => [
            'tier' => 1,
            'sync_order' => 20,
            'strategy' => 'composite_pk',
            'primary_key' => ['role_id', 'model_id', 'model_type'],
            'depends_on' => ['roles', 'users'],
        ],
        'role_has_permissions' => [
            'tier' => 1,
            'sync_order' => 20,
            'strategy' => 'composite_pk',
            'primary_key' => ['permission_id', 'role_id'],
            'depends_on' => ['permissions', 'roles'],
        ],
        'device_model_aliases' => [
            'tier' => 1,
            'sync_order' => 20,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['device_models'],
            'unique_indexes' => [['alias']],
        ],
        'finance_accounts' => [
            'tier' => 1,
            'sync_order' => 20,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['finance_payment_methods', 'finance_expense_categories', 'finance_cash_accounts', 'finance_bank_accounts'],
            'unique_indexes' => [['code']],
        ],
        'team_member_work_schedules' => [
            'tier' => 2,
            'sync_order' => 20,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
        ],
        'user_assignment_capabilities' => [
            'tier' => 2,
            'sync_order' => 20,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
        ],
        'workforce_employee_salaries' => [
            'tier' => 2,
            'sync_order' => 20,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
        ],

        // --- Tier 1: orders spine (order 30) ---
        'orders' => [
            'tier' => 1,
            'sync_order' => 30,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users', 'device_models'],
            'unique_indexes' => [['order_id'], ['cashfree_payment_id'], ['serial_number']],
            'soft_deletes' => true,
        ],

        // --- Tier 1/2: incidents and related (order 40) ---
        'incidents' => [
            'tier' => 1,
            'sync_order' => 40,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['orders', 'users'],
            'unique_indexes' => [['reference_no']],
            'soft_deletes' => true,
        ],
        'approval_numbers' => [
            'tier' => 2,
            'sync_order' => 40,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
            'unique_indexes' => [['approval_number']],
            'soft_deletes' => true,
        ],
        'cashfree_webhook_logs' => [
            'tier' => 1,
            'sync_order' => 40,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['orders'],
        ],
        'incident_waiting_states' => [
            'tier' => 2,
            'sync_order' => 40,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incidents'],
        ],
        'service_case_close_outcomes' => [
            'tier' => 1,
            'sync_order' => 40,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incidents'],
        ],
        'service_case_close_exceptions' => [
            'tier' => 1,
            'sync_order' => 40,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incidents'],
        ],
        'incident_bonvoice_call_links' => [
            'tier' => 1,
            'sync_order' => 40,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incidents'],
        ],
        'business_holds' => [
            'tier' => 2,
            'sync_order' => 40,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incidents'],
        ],

        // --- Tier 1/2: child records (order 50) ---
        'remarks' => [
            'tier' => 2,
            'sync_order' => 50,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incidents', 'users'],
        ],
        'remark_mentions' => [
            'tier' => 2,
            'sync_order' => 50,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['remarks', 'users'],
        ],
        'refund_requests' => [
            'tier' => 1,
            'sync_order' => 50,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['orders', 'incidents', 'users'],
            'unique_indexes' => [['reference_no']],
            'soft_deletes' => true,
        ],
        'approval_incident' => [
            'tier' => 2,
            'sync_order' => 50,
            'strategy' => 'composite_pk',
            'primary_key' => ['approval_number_id', 'incident_id'],
            'created_at' => 'created_at',
            'depends_on' => ['approval_numbers', 'incidents', 'users'],
        ],
        'customer_data_corrections' => [
            'tier' => 1,
            'sync_order' => 50,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['orders', 'users'],
        ],
        'customer_data_correction_items' => [
            'tier' => 1,
            'sync_order' => 50,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['customer_data_corrections'],
        ],
        'commercial_service_restorations' => [
            'tier' => 1,
            'sync_order' => 50,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['orders', 'refund_requests'],
        ],
        'support_appointments' => [
            'tier' => 2,
            'sync_order' => 50,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incidents'],
        ],
        'notification_link_tokens' => [
            'tier' => 2,
            'sync_order' => 50,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incidents', 'orders'],
        ],
        'notification_link_clicks' => [
            'tier' => 2,
            'sync_order' => 50,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['notification_link_tokens'],
        ],

        // --- Tier 1: finance ledger (order 60) ---
        'finance_journals' => [
            'tier' => 1,
            'sync_order' => 60,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['finance_accounts', 'users'],
            'unique_indexes' => [['journal_no'], ['idempotency_key']],
        ],
        'finance_journal_lines' => [
            'tier' => 1,
            'sync_order' => 60,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['finance_journals', 'finance_accounts'],
        ],
        'finance_expenses' => [
            'tier' => 1,
            'sync_order' => 60,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['finance_journals', 'finance_expense_categories'],
        ],
        'cash_book_entries' => [
            'tier' => 1,
            'sync_order' => 60,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['finance_journals', 'users'],
            'unique_indexes' => [['entry_no']],
            'soft_deletes' => true,
        ],

        // --- Tier 1/2: IRA / email learning (order 70) ---
        'ira_memories' => [
            'tier' => 1,
            'sync_order' => 70,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
            'unique_indexes' => [['uuid']],
            'soft_deletes' => true,
        ],
        'ira_memory_relations' => [
            'tier' => 2,
            'sync_order' => 70,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['ira_memories'],
        ],

        // --- Tier 2: integrations and messaging (order 80) ---
        'outbox_events' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['idempotency_key']],
        ],
        'interakt_messages' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['message_id']],
        ],
        'interakt_webhook_logs' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'bonvoice_webhook_logs' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'bonvoice_call_events' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['call_id', 'leg']],
        ],
        'bonvoice_call_alerts' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['call_id']],
        ],
        'whatsapp_template_dispatches' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'telegram_notifications' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'notifications' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'uuid_pk',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'automation_executions' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incident_waiting_states'],
            'unique_indexes' => [['idempotency_key']],
        ],
        'reminders' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['idempotency_key']],
        ],
        'ira_notifications' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'ira_operational_memory_snapshots' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'ira_insight_feedback' => [
            'tier' => 2,
            'sync_order' => 80,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],

        // --- Tier 2/4: email (order 90) ---
        'gmail_mailbox_sync_states' => [
            'tier' => 2,
            'sync_order' => 90,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['mailbox']],
        ],
        'gmail_sync_message_failures' => [
            'tier' => 2,
            'sync_order' => 90,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'incoming_email_messages' => [
            'tier' => 4,
            'sync_order' => 90,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['ira_memories'],
            'unique_indexes' => [['rfc_message_id'], ['provider', 'provider_message_id']],
        ],
        'outgoing_email_messages' => [
            'tier' => 2,
            'sync_order' => 90,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'incident_incoming_email_links' => [
            'tier' => 2,
            'sync_order' => 90,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incidents', 'incoming_email_messages'],
            'unique_indexes' => [['incoming_email_message_id']],
        ],
        'incoming_email_ignore_stats' => [
            'tier' => 2,
            'sync_order' => 90,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['stat_date', 'reason']],
        ],
        'conversation_workspace_sessions' => [
            'tier' => 2,
            'sync_order' => 90,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['incidents'],
        ],

        // --- Tier 2: workforce (order 100) ---
        'leave_requests' => [
            'tier' => 2,
            'sync_order' => 100,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
        ],
        'leave_request_amendments' => [
            'tier' => 2,
            'sync_order' => 100,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['leave_requests'],
        ],
        'work_sessions' => [
            'tier' => 2,
            'sync_order' => 100,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
        ],
        'workforce_attendance_days' => [
            'tier' => 2,
            'sync_order' => 100,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
            'unique_indexes' => [['user_id', 'work_date']],
        ],
        'workforce_short_attendance_reviews' => [
            'tier' => 2,
            'sync_order' => 100,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
            'unique_indexes' => [['user_id', 'work_date']],
        ],
        'workforce_payroll_month_locks' => [
            'tier' => 2,
            'sync_order' => 100,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'workforce_payroll_month_runs' => [
            'tier' => 2,
            'sync_order' => 100,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'workforce_payroll_run_lines' => [
            'tier' => 2,
            'sync_order' => 100,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['workforce_payroll_month_runs', 'users'],
        ],
        'workforce_recognition_reviews' => [
            'tier' => 2,
            'sync_order' => 100,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
        ],
        'todos' => [
            'tier' => 2,
            'sync_order' => 100,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['users'],
        ],

        // --- Tier 2: ops / repair (order 110) ---
        'system_repair_batches' => [
            'tier' => 2,
            'sync_order' => 110,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'system_repair_items' => [
            'tier' => 2,
            'sync_order' => 110,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'depends_on' => ['system_repair_batches'],
        ],

        // --- Tier 4: append-only / large audit (order 120) ---
        'audit_logs' => [
            'tier' => 4,
            'sync_order' => 120,
            'strategy' => 'bigint_id_insert_only',
            'primary_key' => ['id'],
            'created_at' => 'created_at',
        ],
        'executive_metric_snapshots' => [
            'tier' => 4,
            'sync_order' => 120,
            'strategy' => 'bigint_id_insert_only',
            'primary_key' => ['id'],
            'created_at' => 'created_at',
            'unique_indexes' => [['metric_key', 'snapshot_time', 'granularity']],
        ],
        'performance_intelligence_snapshots' => [
            'tier' => 4,
            'sync_order' => 120,
            'strategy' => 'bigint_id+updated_at',
            'primary_key' => ['id'],
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
            'unique_indexes' => [['user_id', 'snapshot_date']],
        ],
    ],

];
