<?php

return [
    'api_key' => env('INTERAKT_API_KEY'),
    'webhook_secret' => env('INTERAKT_WEBHOOK_SECRET'),
    'base_url' => rtrim((string) env('INTERAKT_BASE_URL', 'https://api.interakt.ai'), '/'),
    'verify_signature' => filter_var(env('INTERAKT_VERIFY_SIGNATURE', false), FILTER_VALIDATE_BOOLEAN),
    'timeout_seconds' => (int) env('INTERAKT_TIMEOUT_SECONDS', 15),
    'connect_timeout_seconds' => (int) env('INTERAKT_CONNECT_TIMEOUT_SECONDS', 5),
    'max_retries' => (int) env('INTERAKT_MAX_RETRIES', 3),
    'retry_delay_ms' => (int) env('INTERAKT_RETRY_DELAY_MS', 200),
    'app_url' => rtrim((string) env('INTERAKT_APP_URL', 'https://app.interakt.ai'), '/'),
    'conversation_url_template' => env('INTERAKT_CONVERSATION_URL_TEMPLATE'),
    'customer_profile_url_template' => env(
        'INTERAKT_CUSTOMER_PROFILE_URL_TEMPLATE',
        '{app_url}/contacts?search={phone}',
    ),
    'flow_token_ttl_hours' => (int) env('INTERAKT_FLOW_TOKEN_TTL_HOURS', 24),
    'flow_id' => env('INTERAKT_FLOW_ID'),
    'templates' => [
        'request_serial_number' => [
            'name' => env('INTERAKT_TEMPLATE_REQUEST_SERIAL'),
            'language_code' => env('INTERAKT_TEMPLATE_REQUEST_SERIAL_LANGUAGE', 'en'),
            'language_code_is_default' => ! filled(env('INTERAKT_TEMPLATE_REQUEST_SERIAL_LANGUAGE')),
            'display_name' => env('INTERAKT_TEMPLATE_REQUEST_SERIAL_DISPLAY', 'Order Update'),
            'purpose' => 'Request Serial Number',
            'internal_note' => 'Requested serial number from customer via approved WhatsApp template.',
        ],
        'repair_started' => [
            'name' => env('INTERAKT_TEMPLATE_REPAIR_STARTED'),
            'language_code' => env('INTERAKT_TEMPLATE_REPAIR_STARTED_LANGUAGE', 'en'),
            'language_code_is_default' => ! filled(env('INTERAKT_TEMPLATE_REPAIR_STARTED_LANGUAGE')),
            'display_name' => env('INTERAKT_TEMPLATE_REPAIR_STARTED_DISPLAY', 'Repair Started'),
            'purpose' => 'Repair Started',
        ],
        'repair_completed' => [
            'name' => env('INTERAKT_TEMPLATE_REPAIR_COMPLETED'),
            'language_code' => env('INTERAKT_TEMPLATE_REPAIR_COMPLETED_LANGUAGE', 'en'),
            'language_code_is_default' => ! filled(env('INTERAKT_TEMPLATE_REPAIR_COMPLETED_LANGUAGE')),
            'display_name' => env('INTERAKT_TEMPLATE_REPAIR_COMPLETED_DISPLAY', 'Repair Completed'),
            'purpose' => 'Repair Completed',
        ],
        'ready_for_dispatch' => [
            'name' => env('INTERAKT_TEMPLATE_READY_FOR_DISPATCH'),
            'language_code' => env('INTERAKT_TEMPLATE_READY_FOR_DISPATCH_LANGUAGE', 'en'),
            'language_code_is_default' => ! filled(env('INTERAKT_TEMPLATE_READY_FOR_DISPATCH_LANGUAGE')),
            'display_name' => env('INTERAKT_TEMPLATE_READY_FOR_DISPATCH_DISPLAY', 'Ready for Dispatch'),
            'purpose' => 'Ready for Dispatch',
        ],
        'refund_update' => [
            'name' => env('INTERAKT_TEMPLATE_REFUND_UPDATE'),
            'language_code' => env('INTERAKT_TEMPLATE_REFUND_UPDATE_LANGUAGE', 'en'),
            'language_code_is_default' => ! filled(env('INTERAKT_TEMPLATE_REFUND_UPDATE_LANGUAGE')),
            'display_name' => env('INTERAKT_TEMPLATE_REFUND_UPDATE_DISPLAY', 'Refund Update'),
            'purpose' => 'Refund Update',
        ],
        'amc_reminder' => [
            'name' => env('INTERAKT_TEMPLATE_AMC_REMINDER'),
            'language_code' => env('INTERAKT_TEMPLATE_AMC_REMINDER_LANGUAGE', 'en'),
            'language_code_is_default' => ! filled(env('INTERAKT_TEMPLATE_AMC_REMINDER_LANGUAGE')),
            'display_name' => env('INTERAKT_TEMPLATE_AMC_REMINDER_DISPLAY', 'AMC Reminder'),
            'purpose' => 'AMC Reminder',
        ],
        'support_appointment_booked' => [
            'name' => env('INTERAKT_TEMPLATE_SUPPORT_APPOINTMENT_BOOKED'),
            'language_code' => env('INTERAKT_TEMPLATE_SUPPORT_APPOINTMENT_BOOKED_LANGUAGE', 'en'),
            'language_code_is_default' => ! filled(env('INTERAKT_TEMPLATE_SUPPORT_APPOINTMENT_BOOKED_LANGUAGE')),
            'display_name' => env('INTERAKT_TEMPLATE_SUPPORT_APPOINTMENT_BOOKED_DISPLAY', 'Support Appointment Booked'),
            'purpose' => 'Support Appointment Booked',
            'internal_note' => 'Confirms support appointment booking with preferred date and time slot.',
        ],
    ],
];
