<?php

return [
    'categories' => [
        'performance' => [
            'label' => 'Performance',
            'description' => 'Runtime performance controls — polling, profiles, and hybrid realtime.',
            'icon' => 'bi-speedometer2',
            'sort' => 5,
        ],
        'system' => [
            'label' => 'System',
            'description' => 'Core platform behaviour and diagnostics.',
            'icon' => 'bi-cpu',
            'sort' => 10,
        ],
        'notifications' => [
            'label' => 'Notifications',
            'description' => 'Channel-agnostic notification dispatch controls.',
            'icon' => 'bi-bell',
            'sort' => 15,
        ],
        'whatsapp' => [
            'label' => 'WhatsApp',
            'description' => 'WhatsApp API and automation feature flags.',
            'icon' => 'bi-whatsapp',
            'sort' => 20,
        ],
        'email' => [
            'label' => 'Email',
            'description' => 'Email channel integration flags.',
            'icon' => 'bi-envelope',
            'sort' => 30,
        ],
        'telegram' => [
            'label' => 'Telegram',
            'description' => 'Telegram channel integration flags.',
            'icon' => 'bi-telegram',
            'sort' => 40,
        ],
        'outbox' => [
            'label' => 'Outbox',
            'description' => 'Outbound message processing controls.',
            'icon' => 'bi-send',
            'sort' => 50,
        ],
        'ira' => [
            'label' => 'IRA',
            'description' => 'Intelligent response assistant controls.',
            'icon' => 'bi-stars',
            'sort' => 60,
        ],
        'automation' => [
            'label' => 'Automation',
            'description' => 'Waiting-state automation scheduler and execution controls.',
            'icon' => 'bi-robot',
            'sort' => 70,
        ],
    ],

    'settings' => [
        'system.debug_mode' => [
            'category' => 'system',
            'label' => 'Debug mode',
            'description' => 'Enable verbose diagnostics for troubleshooting.',
            'type' => 'boolean',
            'default' => false,
        ],
        'notifications.whatsapp.enabled' => [
            'category' => 'notifications',
            'label' => 'WhatsApp notifications',
            'description' => 'Allow the notification dispatcher to send WhatsApp messages.',
            'type' => 'boolean',
            'default' => true,
        ],
        'notifications.email.enabled' => [
            'category' => 'notifications',
            'label' => 'Email notifications',
            'description' => 'Allow the notification dispatcher to send email messages.',
            'type' => 'boolean',
            'default' => false,
        ],
        'notifications.desktop.enabled' => [
            'category' => 'notifications',
            'label' => 'Desktop notifications',
            'description' => 'Allow the notification dispatcher to send desktop push notifications.',
            'type' => 'boolean',
            'default' => false,
        ],
        'notifications.telegram.enabled' => [
            'category' => 'notifications',
            'label' => 'Telegram notifications',
            'description' => 'Allow the notification dispatcher to send Telegram messages.',
            'type' => 'boolean',
            'default' => false,
        ],
        'whatsapp.api_enabled' => [
            'category' => 'whatsapp',
            'label' => 'WhatsApp API',
            'description' => 'Allow outbound WhatsApp API calls.',
            'type' => 'boolean',
            'default' => true,
        ],
        'whatsapp.manual_templates_enabled' => [
            'category' => 'whatsapp',
            'label' => 'Manual templates',
            'description' => 'Allow agents to send manual WhatsApp templates.',
            'type' => 'boolean',
            'default' => true,
        ],
        'whatsapp.automation_enabled' => [
            'category' => 'whatsapp',
            'label' => 'WhatsApp automation',
            'description' => 'Enable automated WhatsApp workflows (future phases).',
            'type' => 'boolean',
            'default' => false,
        ],
        'email.api_enabled' => [
            'category' => 'email',
            'label' => 'Email API',
            'description' => 'Allow outbound email API calls.',
            'type' => 'boolean',
            'default' => true,
        ],
        'telegram.api_enabled' => [
            'category' => 'telegram',
            'label' => 'Telegram API',
            'description' => 'Allow outbound Telegram API calls.',
            'type' => 'boolean',
            'default' => false,
        ],
        'outbox.processor_enabled' => [
            'category' => 'outbox',
            'label' => 'Outbox processor',
            'description' => 'Process queued outbound messages.',
            'type' => 'boolean',
            'default' => true,
        ],
        'ira.enabled' => [
            'category' => 'ira',
            'label' => 'IRA enabled',
            'description' => 'Enable the intelligent response assistant.',
            'type' => 'boolean',
            'default' => true,
        ],
        'automation.scheduler.enabled' => [
            'category' => 'automation',
            'label' => 'Automation scheduler',
            'description' => 'Run the hourly automation scheduler for waiting-state reminders.',
            'type' => 'boolean',
            'default' => false,
        ],
        'performance.profile' => [
            'category' => 'performance',
            'group' => 'profile',
            'label' => 'Performance profile',
            'description' => 'Preset polling configuration. Manual allows individual customization.',
            'type' => 'string',
            'default' => 'balanced',
            'allowed' => ['high_performance', 'balanced', 'low_resource', 'manual'],
        ],
        'performance.polling.dashboard_live_ms' => [
            'category' => 'performance',
            'group' => 'polling',
            'label' => 'Dashboard Live',
            'description' => 'HTTP polling interval for the main dashboard live refresh.',
            'type' => 'integer',
            'default' => 30000,
            'unit' => 'ms',
            'min' => 10000,
            'max' => 300000,
            'recommended' => 30000,
        ],
        'performance.polling.notification_ms' => [
            'category' => 'performance',
            'group' => 'polling',
            'label' => 'Notification Poll',
            'description' => 'Polling interval for the notification bell.',
            'type' => 'integer',
            'default' => 20000,
            'unit' => 'ms',
            'min' => 10000,
            'max' => 120000,
            'recommended' => 20000,
        ],
        'performance.polling.operations_ms' => [
            'category' => 'performance',
            'group' => 'polling',
            'label' => 'Operations Dashboard',
            'description' => 'Polling interval for the Operations Control Center.',
            'type' => 'integer',
            'default' => 30000,
            'unit' => 'ms',
            'min' => 10000,
            'max' => 300000,
            'recommended' => 30000,
        ],
        'performance.polling.operations_full_refresh_ms' => [
            'category' => 'performance',
            'group' => 'polling',
            'label' => 'Operations Full Refresh',
            'description' => 'Interval for periodic full refresh of the Operations dashboard.',
            'type' => 'integer',
            'default' => 120000,
            'unit' => 'ms',
            'min' => 30000,
            'max' => 600000,
            'recommended' => 120000,
        ],
        'performance.polling.customer360_timeline_ms' => [
            'category' => 'performance',
            'group' => 'polling',
            'label' => 'Customer360 Timeline',
            'description' => 'Polling interval for Customer 360 timeline updates.',
            'type' => 'integer',
            'default' => 30000,
            'unit' => 'ms',
            'min' => 10000,
            'max' => 300000,
            'recommended' => 30000,
        ],
        'performance.polling.customer360_device_sync_ms' => [
            'category' => 'performance',
            'group' => 'polling',
            'label' => 'Customer360 Device Sync',
            'description' => 'Polling interval for Customer 360 device sync status.',
            'type' => 'integer',
            'default' => 10000,
            'unit' => 'ms',
            'min' => 5000,
            'max' => 60000,
            'recommended' => 10000,
        ],
        'performance.polling.presence_heartbeat_seconds' => [
            'category' => 'performance',
            'group' => 'polling',
            'label' => 'Presence Heartbeat',
            'description' => 'Interval between presence heartbeat pings.',
            'type' => 'integer',
            'default' => 120,
            'unit' => 'seconds',
            'min' => 30,
            'max' => 600,
            'recommended' => 120,
        ],
        'performance.polling.agent_reminder_seconds' => [
            'category' => 'performance',
            'group' => 'polling',
            'label' => 'Agent Reminder Timer',
            'description' => 'Interval for agent appointment reminder checks.',
            'type' => 'integer',
            'default' => 60,
            'unit' => 'seconds',
            'min' => 30,
            'max' => 300,
            'recommended' => 60,
        ],
        'performance.polling.executive_dashboard_seconds' => [
            'category' => 'performance',
            'group' => 'polling',
            'label' => 'Executive Dashboard',
            'description' => 'Reserved for future Executive Command Center auto-refresh. Not wired yet.',
            'type' => 'integer',
            'default' => 60,
            'unit' => 'seconds',
            'min' => 30,
            'max' => 600,
            'recommended' => 60,
            'disabled' => true,
        ],
        'hybrid_realtime.reference_number' => [
            'category' => 'performance',
            'group' => 'hybrid_realtime',
            'label' => 'Reference Number',
            'description' => 'Broadcast lightweight Reference Number updates over Reverb. When off, dashboards rely on polling.',
            'type' => 'boolean',
            'default' => false,
        ],
        'hybrid_realtime.assignment' => [
            'category' => 'performance',
            'group' => 'hybrid_realtime',
            'label' => 'Assignment',
            'description' => 'Broadcast lightweight Assignment updates over Reverb. When off, dashboards rely on polling.',
            'type' => 'boolean',
            'default' => false,
        ],
        'hybrid_realtime.close_resolve' => [
            'category' => 'performance',
            'group' => 'hybrid_realtime',
            'label' => 'Close / Resolve',
            'description' => 'Broadcast lightweight Close and Resolve updates over Reverb. When off, dashboards rely on polling.',
            'type' => 'boolean',
            'default' => false,
        ],
        'hybrid_realtime.incoming_calls' => [
            'category' => 'performance',
            'group' => 'hybrid_realtime',
            'label' => 'Incoming Calls',
            'description' => 'Broadcast lightweight incoming call cards over Reverb. When off, agents rely on polling and legacy notifications.',
            'type' => 'boolean',
            'default' => false,
        ],
        'hybrid_realtime.desktop_notifications' => [
            'category' => 'performance',
            'group' => 'hybrid_realtime',
            'label' => 'Desktop Notifications',
            'description' => 'Deliver actionable realtime notifications (toast, browser, notification center) over Reverb.',
            'type' => 'boolean',
            'default' => false,
        ],
        'hybrid_realtime.operator_alerts' => [
            'category' => 'performance',
            'group' => 'hybrid_realtime',
            'label' => 'Operator Alerts',
            'description' => 'Broadcast operator alerts (assignments, SLA, transfers) over Reverb with priority handling.',
            'type' => 'boolean',
            'default' => false,
        ],
        'performance.notifications.toast_duration_ms' => [
            'category' => 'performance',
            'group' => 'notifications',
            'label' => 'Toast duration',
            'description' => 'How long non-critical notification toasts remain visible.',
            'type' => 'integer',
            'default' => 5000,
            'unit' => 'ms',
            'min' => 2000,
            'max' => 30000,
            'recommended' => 5000,
        ],
        'performance.notifications.sound_enabled' => [
            'category' => 'performance',
            'group' => 'notifications',
            'label' => 'Notification sound',
            'description' => 'Play a sound for high-priority operator alerts.',
            'type' => 'boolean',
            'default' => true,
        ],
        'performance.notifications.browser_enabled' => [
            'category' => 'performance',
            'group' => 'notifications',
            'label' => 'Browser notifications',
            'description' => 'Show browser notifications for Critical and High priority alerts.',
            'type' => 'boolean',
            'default' => true,
        ],
        'performance.notifications.priority_threshold' => [
            'category' => 'performance',
            'group' => 'notifications',
            'label' => 'Priority threshold',
            'description' => 'Minimum priority level delivered to operators. Silent alerts appear in the notification center only.',
            'type' => 'string',
            'default' => 'normal',
            'allowed' => ['silent', 'normal', 'high', 'critical'],
        ],
        'performance.notifications.quiet_hours_enabled' => [
            'category' => 'performance',
            'group' => 'notifications',
            'label' => 'Quiet hours',
            'description' => 'Future — suppress non-critical notifications during configured quiet hours.',
            'type' => 'boolean',
            'default' => false,
            'disabled' => true,
        ],
    ],
];
