<?php

return [
    'dashboard' => [
        'modules' => [
            'all' => [
                'label' => 'All',
                'icon' => 'bi-grid-3x3-gap-fill',
            ],
            'service_cases' => [
                'label' => 'Service Cases',
                'icon' => 'bi-clipboard-data',
            ],
            'hardware_orders' => [
                'label' => 'Hardware Orders',
                'icon' => 'bi-box-seam',
            ],
        ],
    ],
    'service_case' => [
        'singular' => 'Service Case',
        'plural' => 'Service Cases',
        'reference_label' => 'Service Case ID',
        'reference_short' => 'Case ID',
        'log_action' => 'Log Service Case',
        'create_action' => 'Create Service Case',
        'view_all' => 'View all service cases',
        'empty' => 'No service cases found.',
        'search_placeholder' => 'Search service cases...',
        'link_action' => 'Link Service Cases',
        'linked_empty' => 'No service cases linked.',
        'select_label' => 'Service Case',
        'select_optional' => 'Service Case (optional)',
        'select_prompt' => 'Select an order first, then search service cases...',
        'selected_prefix' => 'Selected service case',
        'no_selection' => 'No service cases selected yet.',
        'delete_confirm' => 'Are you sure you want to delete this service case?',
        'information_heading' => 'Service Case Information',
        'related_heading' => 'Service Case History',
        'history_heading' => 'Service Case History',
        'history_empty' => 'No service cases linked to this order yet.',
        'create_new_action' => 'Create New Service Case',
        'continue_creating_action' => 'Continue Creating',
        'open_existing_action' => 'Open Existing Service Case',
        'active_banner_heading' => 'Active Service Case Exists',
        'order_found_message' => 'Existing order found. Review service case history before creating a new case.',
        'previous_cases_heading' => 'Previous Service Cases',
        'guidance_heading' => 'When to create a new service case',
        'guidance_create' => 'Create a new service case for a new complaint, different issue, customer return after closure, fresh SLA, or new support request.',
        'guidance_remarks' => 'Use remarks on an existing service case for status enquiries, follow-ups, assignment updates, engineer updates, and internal notes.',
        'open_label' => 'Open Service Cases',
        'resolved_label' => 'Resolved Service Cases',
        'closed_label' => 'Closed Service Cases',
        'activity_timeline_heading' => 'Activity Timeline',
        'issue_summary_heading' => 'Issue Summary',
        'problem_description_heading' => 'Problem Description',
        'customer_order_heading' => 'Customer & Order Summary',
        'related_information_heading' => 'Related Information',
        'quick_actions_heading' => 'Quick Actions',
        'shortcuts_hint' => 'Shortcuts: R remark · A assign · E edit · / search · Esc close dialog',
    ],
];
