@include('service-cases.fragments.action-remark-form', [
    'action' => 'close',
    'incident' => $incident,
    'title' => 'Close Service Case',
    'description' => 'Close this service case. Add a remark describing the final outcome.',
    'submitLabel' => 'Close Service Case',
    'submitIcon' => 'bi-x-circle',
    'submitBtnClass' => 'btn-secondary',
    'modalLabelId' => 'closeModalLabel',
    'statusValue' => 'closed',
    'workspaceActionUrl' => $workspaceActionUrl ?? null,
    'workspaceContext' => $workspaceContext ?? null,
    'mentionUsers' => $mentionUsers ?? [],
    'remarkBody' => $remarkBody ?? null,
])
