@include('service-cases.fragments.action-remark-form', [
    'action' => 'resolve',
    'incident' => $incident,
    'title' => 'Resolve Service Case',
    'description' => 'Mark this service case as resolved. Add a remark describing what was completed.',
    'submitLabel' => 'Resolve',
    'submitIcon' => 'bi-check-circle',
    'submitBtnClass' => 'btn-success',
    'modalLabelId' => 'resolveModalLabel',
    'statusValue' => 'resolved',
    'workspaceActionUrl' => $workspaceActionUrl ?? null,
    'workspaceContext' => $workspaceContext ?? null,
    'mentionUsers' => $mentionUsers ?? [],
    'remarkBody' => $remarkBody ?? null,
])
